##################################
#04/02/2020

#VST Normalization --> Plotting PCAs

#Purpose:
#1) Normalize raw consensus count matrix using VST-normalization
#2) Output and use VST-normalized count matrices to generate PCAs
#3) Generate heatmaps with raw count matrices


##################################
rm(list=ls())
library("DESeq2")
library("ggplot2")
library(ChIPseeker)
library("pheatmap")
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
set.seed(42)



setwd("~/Dropbox/RWY_ATAC_Code_Checking/")
#First, import the consensus count matrix of raw reads generated by 
consensus_count_matrix <- read.table("IN_VITRO/Output_Data_InVitro/invitro_consensus_countMatrix_Raw.txt", header=TRUE, sep="\t")

print(colnames(consensus_count_matrix))
#[1] "CHR"      "START"    "END"      "Y_aNSC_2" "Y_aNSC_3" "Y_aNSC_4" "O_aNSC_1" "O_aNSC_2" "O_aNSC_4" "Y_qNSC_1" "Y_qNSC_2" "O_qNSC_2" "O_qNSC_3"

###Generate a heatmap of all libraries using Pearson's correlation
pdf("IN_VITRO/Output_Figs_InVitro/InVitro_consensus_Raw_heatmap_pearson.pdf")
pheatmap(cor(consensus_count_matrix[,c(4:13)], method="pearson"))
dev.off()


#Manually create sampleTable
sampleTable<-  colnames(consensus_count_matrix[,c(4:13)])
sampleTable<- as.data.frame(sampleTable)
names(sampleTable)[1]<- "Sample"
sampleTable$Age <- c(rep(c("Young"),3),rep(c("Old"),3),rep(c("Young"),2),rep(c("Old"),2))
sampleTable$Cell_Type <- c(rep(c("aNSC"),6),rep(c("qNSC"),4))
sampleTable$Group <- c(rep(c("Y_aNSC"),3),rep(c("O_aNSC"),3),rep(c("Y_qNSC"),2),rep(c("O_qNSC"),2))
str(sampleTable)

#Create dds object
dds <- DESeqDataSetFromMatrix(countData=consensus_count_matrix[,c(4:13)], sampleTable, ~Group)

dds$Age <- as.factor(dds$Age)
dds$Age <- relevel(dds$Age, ref="Young")
dds$Cell_Type <- as.factor(dds$Cell_Type)
dds$Group <- as.factor(dds$Group)

#Calling DESEQ to calculate dispersion estimates
dds <- DESeq(dds)

#Using VST to normalize data
vst <- varianceStabilizingTransformation(dds, blind =F)
vstMat <- assay(vst)

pca.vst <- prcomp(t(vstMat), scale = F)
summary(pca.vst)

#format for ggplot
pca.vst.df <- as.data.frame(pca.vst$x)
str(pca.vst.df)
pca.vst.df$Age <- c(rep(c("Young"),3),rep(c("Old"),3),rep(c("Young"),2),rep(c("Old"),2))
pca.vst.df$Cell_Type <- c(rep(c("aNSC"),6),rep(c("qNSC"),4))
pca.vst.df$Group <- c(rep(c("Y_aNSC"),3),rep(c("O_aNSC"),3),rep(c("Y_qNSC"),2),rep(c("O_qNSC"),2))

#Y_qNSC lightskyblue
#O_qNSC dodgerblue
#Y_aNSC orange
#O_aNSC red2


theme<-theme(panel.background = element_blank(),panel.border=element_rect(fill=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),strip.background=element_blank(),
             axis.text=element_text(colour="black", size=rel(2)),axis.ticks=element_line(colour="black"),plot.margin=unit(c(1,1,1,1),"line"),
             legend.title = element_text(color = "black", size = 20),legend.text = element_text(color = "black", size = 16))


pdf("IN_VITRO/Output_Figs_InVitro/InVitro_Y_O_Q_A_PC1_PC2.pdf",height=10,width=12)
ggplot(pca.vst.df, aes(PC1,PC2, color=pca.vst.df$Group)) +
  geom_point(size=12, shape=18)+
  scale_color_manual(values=c("lightskyblue","orange","dodgerblue","red2"),breaks=c("Y_qNSC","Y_aNSC","O_qNSC","O_aNSC"),labels=c("Young qNSC","Young aNSC","Old qNSC","Old aNSC"), name="")+
  ggtitle("PCA - qNSC and aNSCs") +
  xlab("PC1 (60.40%)")+
  ylab("PC2 (8.15%)")+
  theme
dev.off()

pdf("IN_VITRO/Output_Figs_InVitro/InVitro_Y_O_Q_A_PC1_PC3.pdf",height=10,width=12)
ggplot(pca.vst.df, aes(PC1,PC3, color=pca.vst.df$Group)) +
  geom_point(size=12, shape=18)+
  scale_color_manual(values=c("lightskyblue","orange","dodgerblue","red2"),breaks=c("Y_qNSC","Y_aNSC","O_qNSC","O_aNSC"),labels=c("Young qNSC","Young aNSC","Old qNSC","Old aNSC"), name="")+
  ggtitle("PCA - qNSC and aNSCs") +
  xlab("PC1 (60.40%)")+
  ylab("PC3 (5.87%)")+
  theme
dev.off()

pdf("IN_VITRO/Output_Figs_InVitro/InVitro_Y_O_Q_A_PC1_PC4.pdf",height=10,width=12)
ggplot(pca.vst.df, aes(PC1,PC4, color=pca.vst.df$Group)) +
  geom_point(size=12, shape=18)+
  scale_color_manual(values=c("lightskyblue","orange","dodgerblue","red2"),breaks=c("Y_qNSC","Y_aNSC","O_qNSC","O_aNSC"),labels=c("Young qNSC","Young aNSC","Old qNSC","Old aNSC"), name="")+
  ggtitle("PCA - qNSC and aNSCs") +
  xlab("PC1 (60.40%)")+
  ylab("PC4 (5.33%)")+
  theme
dev.off()





######################################################################################################
#Visualziing qNSC and aNSC libraries from both in vivo and in vitro experiments on the same heatmaps/PCAs
######################################################################################################
rm(list=ls())
library("DESeq2")
library("ggplot2")
library(ChIPseeker)
library("pheatmap")
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
set.seed(42)



setwd("~/Dropbox/RWY_ATAC_Code_Checking/")
#First, import the consensus count matrix of raw reads generated by 
consensus_count_matrix <- read.table("IN_VITRO/Output_Data_InVitro/Combined_InVitro_InVivo_countMatrix_Raw.txt", header=TRUE, sep="\t")

print(colnames(consensus_count_matrix))
#[1] "CHR"              "START"            "END"              "Y_qNSC_1_invivo"  "Y_aNSC_1_invivo"  "O_qNSC_1_invivo"  "O_aNSC_1_invivo"  "Y_qNSC_2_invivo"  "O_qNSC_2_invivo" 
#[10] "O_aNSC_2_invivo"  "Y_qNSC_3_invivo"  "Y_aNSC_3_invivo"  "O_qNSC_3_invivo"  "O_aNSC_3_invivo"  "Y_aNSC_2_invitro" "Y_aNSC_3_invitro" "Y_aNSC_4_invitro" "O_aNSC_1_invitro"
#[19] "O_aNSC_2_invitro" "O_aNSC_4_invitro" "Y_qNSC_1_invitro" "Y_qNSC_2_invitro" "O_qNSC_2_invitro" "O_qNSC_3_invitro"

###Generate a heatmap of all libraries using Pearson's correlation
pdf("IN_VITRO/Output_Figs_InVitro/Combined_InVitro_InVivo_consensus_Raw_heatmap_pearson.pdf")
pheatmap(cor(consensus_count_matrix[,c(4:24)], method="pearson"))
dev.off()

#Manually create sampleTable
sampleTable<-  colnames(consensus_count_matrix[,c(4:24)])
sampleTable<- as.data.frame(sampleTable)
names(sampleTable)[1]<- "Sample"
sampleTable$Age <- c(rep(c("Young"),2),rep(c("Old"),2),rep(c("Young"),1),rep(c("Old"),2),rep(c("Young"),2),rep(c("Old"),2),rep(c("Young"),3),rep(c("Old"),3),rep(c("Young"),2),rep(c("Old"),2))
sampleTable$Cell_Type <- c("qNSC","aNSC","qNSC","aNSC","qNSC","qNSC","aNSC","qNSC","aNSC","qNSC","aNSC",rep(c("aNSC"),6),rep(c("qNSC"),4))
sampleTable$Group <- c("Y_qNSC_invivo","Y_aNSC_invivo","O_qNSC_invivo","O_aNSC_invivo","Y_qNSC_invivo","O_qNSC_invivo","O_aNSC_invivo","Y_qNSC_invivo","Y_aNSC_invivo",
                       "O_qNSC_invivo","O_aNSC_invivo",rep(c("Y_aNSC_invitro"),3),rep(c("O_aNSC_invitro"),3),rep(c("Y_qNSC_invitro"),2),rep(c("O_qNSC_invitro"),2))
sampleTable$Condition <- c(rep(c("In Vivo"),11),rep(c("In Vitro"),10))
str(sampleTable)

#Create dds object
dds <- DESeqDataSetFromMatrix(countData=consensus_count_matrix[,c(4:24)], sampleTable, ~Group)

dds$Age <- as.factor(dds$Age)
dds$Age <- relevel(dds$Age, ref="Young")
dds$Cell_Type <- as.factor(dds$Cell_Type)
dds$Group <- as.factor(dds$Group)
dds$Condition <- as.factor(dds$Condition)

#Calling DESEQ to calculate dispersion estimates
dds <- DESeq(dds)

#Using VST to normalize data
vst <- varianceStabilizingTransformation(dds, blind =F)
vstMat <- assay(vst)

pca.vst <- prcomp(t(vstMat), scale = F)
summary(pca.vst)

#format for ggplot
pca.vst.df <- as.data.frame(pca.vst$x)
str(pca.vst.df)
pca.vst.df$Age <- sampleTable$Age
pca.vst.df$Cell_Type <- sampleTable$Cell_Type
pca.vst.df$Condition <- sampleTable$Condition
pca.vst.df$Group <- sampleTable$Group

#Y_qNSC lightskyblue
#O_qNSC dodgerblue
#Y_aNSC orange
#O_aNSC red2

theme<-theme(panel.background = element_blank(),panel.border=element_rect(fill=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),strip.background=element_blank(),
             axis.text=element_text(colour="black", size=rel(2)),axis.ticks=element_line(colour="black"),plot.margin=unit(c(1,1,1,1),"line"),
             legend.title = element_text(color = "black", size = 20),legend.text = element_text(color = "black", size = 16))

pdf("IN_VITRO/Output_Figs_InVitro/Combined_InVivo_InVitro_Y_O_Q_A_PC1_PC2.pdf",height=10,width=12)
ggplot(pca.vst.df, aes(PC1,PC2, color=Cell_Type, shape=Age, fill=factor(ifelse(Condition=="In Vitro",Cell_Type,"white")))) +
  scale_color_manual(values=c("red2","dodgerblue"),breaks=c("aNSC","qNSC"),name="Cell Type")+
  scale_shape_manual(values=c(21,24),breaks=c("Old","Young"),name="Age")+
  scale_fill_manual(name="Condition",values=c("red2","dodgerblue","white"))+
  geom_point(size=9)+
  ggtitle("PCA - qNSC and aNSCs") +
  xlab("PC1 (38.48%)")+
  ylab("PC2 (14.36%)")+
  theme +
  geom_point(aes(size = Condition)) +
  scale_size_manual(name = "Condition", breaks=c("In Vivo", "In Vitro"),values = c(9, 9.01)) +
  guides(fill = "none", size = guide_legend(override.aes = list(shape = c(1, 16))))
dev.off()